version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12.9
    working_directory: /go/src/github.com/joshdk/go-junit
    steps:
      - checkout
      - run:
          name: Lint Go code
          command: make lint

  test:
    docker:
    - image: circleci/golang:1.12.9
    working_directory: /go/src/github.com/joshdk/go-junit
    steps:
    - checkout
    - run:
        name: Test Go code
        command: make test
    - store_test_results:
        path: test-results

workflows:
  version: 2
  build:
    jobs:
    - lint
    - test
