name: Test
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "master"

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12

      - name: Run tests
        run: go test -v ./...
